version: "3.7"

services:
  ngnix-server:
    image: nginx-proxy-gateway:v1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  myapp1:
    image: tutum/hello-world
    ports:
      - "8888:80"

  myapp2:
    image: tutum/hello-world
    ports:
      - "9999:80"
